//
// Created by NAMEHERE on 12/4/2021.
//

#ifndef CS3A_KINGS_CORNER_COMPASSENUM_H
#define CS3A_KINGS_CORNER_COMPASSENUM_H

enum CompassENUM {
    NORTH = 1, EAST, SOUTH, WEST, NORTHEAST, SOUTHEAST, SOUTHWEST, NORTHWEST,

    LAST_COMPASS
};

#endif //CS3A_KINGS_CORNER_COMPASSENUM_H
