//
// Created by Adam G. on 11/20/2021.
//

#ifndef CS3A_KINGS_CORNER_RANKSENUM_H
#define CS3A_KINGS_CORNER_RANKSENUM_H

enum RanksENUM {
    ACE = 1, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, TEN, JACK, QUEEN, KING
};

#endif //CS3A_KINGS_CORNER_RANKSENUM_H
