//
// Created by Adam G. on 11/27/2021.
//

#ifndef CS3A_KINGS_CORNER_SFMLFOUNDATIONPILEKING_H
#define CS3A_KINGS_CORNER_SFMLFOUNDATIONPILEKING_H


class SFMLFoundationPileKing {

};


#endif //CS3A_KINGS_CORNER_SFMLFOUNDATIONPILEKING_H
