//
// Created by NAMEHERE on 11/20/2021.
//

#ifndef CS3A_KINGS_CORNER_STATESENUM_H
#define CS3A_KINGS_CORNER_STATESENUM_H

enum StatesENUM {
    HOVERED, HIDDEN, CLICKED,


    LAST_STATES
};

#endif //CS3A_KINGS_CORNER_STATESENUM_H
