//
// Created by Adam G. on 10/1/2023.
//

#ifndef KINGS_CORNER_COMPASSENUM_H
#define KINGS_CORNER_COMPASSENUM_H

enum CompassENUM {
    NORTH = 1, EAST, SOUTH, WEST, NORTHEAST, SOUTHEAST, SOUTHWEST, NORTHWEST,

    LAST_COMPASS
};

#endif //KINGS_CORNER_COMPASSENUM_H
