//
// Created by Adam G. on 11/20/2021.
//

#ifndef STATESENUM_H
#define STATESENUM_H

enum StatesENUM {
    DISABLED, HOVERED, IS_HIDDEN, CLICKED, CHANGE_CURSOR, IS_DRAGGABLE, GUI, ALWAYS_ON_TOP,


    LAST_STATES
};

#endif //STATESENUM_H
