//
// Created by Adam G. on 10/1/2023.
//

#ifndef KINGS_CORNER_SUITSCOLORENUM_H
#define KINGS_CORNER_SUITSCOLORENUM_H

enum SuitsColorENUM {
    RED = 1, BLACK
};

#endif //KINGS_CORNER_SUITSCOLORENUM_H
