//
// Created by Adam G. on 1/16/2022.
//

#ifndef CS8_SIMPLE_CALCULATOR_CALCARITHMETICTYPEENUMS_H
#define CS8_SIMPLE_CALCULATOR_CALCARITHMETICTYPEENUMS_H

enum ArithmeticTypeENUM {
    AT_ADD, AT_SUB,

    LAST_AT
};

#endif //CS8_SIMPLE_CALCULATOR_CALCARITHMETICTYPEENUMS_H
