//
// Created by Adam G. on 1/16/2022.
//

#ifndef CS8_SIMPLE_CALCULATOR_CALCINPUTSENUMS_H
#define CS8_SIMPLE_CALCULATOR_CALCINPUTSENUMS_H

enum inputENUM {
    INPUT_X, INPUT_Y,

    LAST_INPUT
};

#endif //CS8_SIMPLE_CALCULATOR_CALCINPUTSENUMS_H
