//
// Created by Adam G. on 2/23/22.
//

#ifndef CS008_BINARYSEARCHTREE_TRAVERSAL_H
#define CS008_BINARYSEARCHTREE_TRAVERSAL_H

enum Traversal {PREORDER, INORDER, POSTORDER};

#endif //CS008_BINARYSEARCHTREE_TRAVERSAL_H
