//
// Created by Adam G. on 10/21/2021.
//

#ifndef CS3A_POKER_ANALYSIS_RANKSENUM_H
#define CS3A_POKER_ANALYSIS_RANKSENUM_H

enum RanksENUM {
    ACE = 1, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, TEN, JACK, QUEEN, KING
};

#endif //CS3A_POKER_ANALYSIS_RANKSENUM_H
