//
// Created by Adam G. on 10/21/2021.
//

#ifndef CS3A_POKER_ANALYSIS_SUITSENUM_H
#define CS3A_POKER_ANALYSIS_SUITSENUM_H

enum SuitsENUM {
    SPADES = 1, HEARTS, CLUBS, DIAMONDS
};

#endif //CS3A_POKER_ANALYSIS_SUITSENUM_H
